version: '2.0'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-qa
    restart: unless-stopped
    tty: true
    ports:
      - "8008:8000"
    volumes:
      - C:\Users\Jonathan C\Documents\laravel\calidad:/var/www/html/
#MySQL Service
  db:
    image: mysql:5.7
    container_name: db-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3346:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # volumes:
    #   - dbdata:/var/lib/mysql/
  #Node Service
  # node:
  #   image: node:18.13.0
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   working_dir: /var/www/html/
  #   volumes:
  #     - ./asapproparts:/var/www/html/
  # db:
  #   image: postgres:9.4-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - '5432:5432'
  #   volumes: 
  #     - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  

